### ISSUE TITLE
New IDE invokeScript 307 error

### ISSUE THREAD

**Issue by AlekseiPupyshev** [wavesplatform/waves-ide#166]
We're trying to run auto-tests from this example:
https://github.com/bodrych/waves-identity/blob/master/tests

Everything works fine here:
https://ide.wavesplatform.com/

**invokeScript** doesn't work here:
https://testnet.ide.wavesplatform.com/

_Error: Transaction is not allowed by account-script_

[new issue] ide.wavesplatform.com doesn't support
let h = await currentHeight()

**Comment by siemarell** [comment]
Hello. testnet.ide is used internally to test some features for future releases. Right now it has compiler and invokeScript format for future TESTNET release which is incompatible with current testnet nodes. As soon as new node version is released on TESTNET ide.wavesplatform.com will be updated.

**Comment by AlekseiPupyshev** [comment]
awesome! thanks! when "new node version is release"? ETA?

**Comment by siemarell** [comment]
Closing, since IDE was updated one week ago
