### ISSUE TITLE
Стандартное значение комиссии недостаточно для деплоя контракт

### ISSUE THREAD

**Issue by IgorShadurin** [wavesplatform/waves-ide#205]
При попытке деплоя кода смарт-контракта выпадает ошибка:
`Error occured. ERROR: { "trace": [ { "result": "ok", "address": "MY_ADDRESS" } ], "error": 112, "message": "State check failed. Reason: Fee for SetScriptTransaction (1000000 in WAVES) does not exceed minimal value of 1400000 WAVES" }`

Ошибка происходит, т.к. в интерфейсе ide комиссия установлена в 1000000 вместо 1400000

**Comment by siemarell** [comment]
Спасибо за репорт. Базовое значение комиссии 1000000. 400000 добавляется для аккаунта, на котором уже есть скрипт. Сейчас IDE не проверяет принадлежит ли senderPublicKey скриптованному аккаунту. Поэтому  комиссию нужно поправить руками в редакторе перед тем, как подписать транзакцию

**Comment by IgorShadurin** [comment]
Спасибо за ответ. Было бы супер, если в будущем такая проверка осуществлялась бы.

**Comment by ilyabettex** [comment]
Что мешает сделать ее по дефолту 14, а не 10? А те, кому критично не платить лишние 0.004 WAVES при первом деплое, пусть руками правят.

**Comment by IgorShadurin** [comment]
Или хотя бы дать возможность менять дефолт на своё усмотрение

вс, 4 авг. 2019 г. в 9:09, ilyabettex <notifications@github.com>:

**Comment by deemru** [comment]
> Спасибо за репорт. Базовое значение комиссии 1000000. 400000 добавляется для аккаунта, на котором уже есть скрипт. Сейчас IDE не проверяет принадлежит ли senderPublicKey скриптованному аккаунту. Поэтому комиссию нужно поправить руками в редакторе перед тем, как подписать транзакцию

Это не решение проблемы, проблема есть, особенно страдают новые пользователи.
