### ISSUE TITLE
Wrong suggest of assetBalance function

### ISSUE THREAD

**Issue by KardanovIR** [wavesplatform/waves-ide#23]
Testnet version of the IDE suggests function called `assetBalance`, but when you click on it you'll see a function called `accountAssetBalance` in the editor.

**Comment by KardanovIR** [comment]
Also `addressFromString` function suggests base58 argument, but it should be a string.
 
![image](https://user-images.githubusercontent.com/1945126/50890838-06566880-140c-11e9-8b09-c26590de3a2a.png)

**Comment by siemarell** [comment]
fixed
