### ISSUE TITLE
IDE fails to compile simple scripts

### ISSUE THREAD

**Issue by alexeykiselev** [wavesplatform/waves-ide#241]
Hello,
I've tried to compile following scripts:

```
Ceiling() == CEILING
```

```
Floor() == FLOOR
```

```
HalfEven() == HALFEVEN
```

```
HalfDown() == HALFDOWN
```

The compilation fails with an error similar to
```
Compilation failed: Can't match inferred types of T over List(HalfDown, HalfUp) in 86-108
```

But, at the same time, the following script could be compiled without errors.

```
Down() == DOWN
```

**Comment by siemarell** [comment]
Hi, thanks for report!
Node API `/utils/compileCode` gives the same result. Waiting for it to be fixed in compiler

**Comment by siemarell** [comment]
Resolved
